[package]
name = "handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
async-std-test = "0.0.4"
async-trait = "0.1.66"
futures = "0.3.26"
http = "0.2.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
